--
-- Source DB setup
--

ALTER SESSION SET CONTAINER=FREEPDB1;

CREATE USER airflow IDENTIFIED BY "9am_27ab61" QUOTA UNLIMITED ON USERS;

GRANT CONNECT, RESOURCE TO airflow;
GRANT SELECT ON v$parameter TO airflow;

create table airflow.types(
    type_id int GENERATED by default on null as IDENTITY,
    type_name varchar2(255) not null
);
comment on table airflow.types is 'Type dictionary table';

create table airflow.types2(
    type_id int GENERATED by default on null as IDENTITY,
    type_name varchar2(255) not null
);

create table airflow.table_data(
    id int GENERATED by default on null as IDENTITY,
    type_id int not null references airflow.types(type_id),
    comments varchar2(255) not null,
    created_ts timestamp not null,
    modified_ts timestamp null
);
comment on table airflow.table_data is 'Data table for standard style transfer';

create table airflow.ods_data(
    id int GENERATED by default on null as IDENTITY,
    type_id int not null references airflow.types(type_id),
    comments varchar2(255) not null,
    created_ts timestamp not null,
    modified_ts timestamp null
);
comment on table airflow.ods_data is 'Data table for ODS-style transfer';

insert into airflow.types(type_id, type_name)
values (1, 'Type 1'), (2, 'Type 2'), (3, 'Type 3');

insert into airflow.types2(type_id, type_name)
values (1, 'Type 1'), (2, 'Type 2'), (3, 'Type 3');

-- insert into airflow.table_data(type_id, comments, created_ts)
-- select floor(random()*3) + 1, md5(random()::varchar2(255)), current_timestamp - '1 day'::interval
-- from generate_series(1, 1000);

-- insert into airflow.ods_data(type_id, comments, created_ts)
-- select floor(random()*3) + 1, md5(random()::varchar2(255)), current_timestamp - '1 day'::interval
-- from generate_series(1, 1000);

